# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

orbs:
  markdown: hux/markdown@0.0.23

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build . --file Dockerfile --tag bl0m1/xtevedocker-ci:<< pipeline.number >>
      - run: echo "$DOCKER_PASS" | docker login --username bl0m1 --password-stdin
      - run: docker push bl0m1/xtevedocker-ci:<< pipeline.number >>
  test:
    working_directory: /xteve
    docker:
      - image: bl0m1/xtevedocker-ci:<< pipeline.number >>
    steps:
      - run: ./xteve -info
      - run: cat /home/xteve/.xteve/settings.json
  publish:
    machine: true
    steps:
      - checkout
      - run: docker build . --file Dockerfile --tag bl0m1/xtevedocker:latest
      - run: echo "$DOCKER_PASS" | docker login --username bl0m1 --password-stdin
      - run: docker push bl0m1/xtevedocker:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - markdown/lint
      - build:
          requires:
            - markdown/lint
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
